<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Pixelbadger.EnterpriseTicTacToe.Application\Pixelbadger.EnterpriseTicTacToe.Application.csproj" />
    <ProjectReference Include="..\Pixelbadger.EnterpriseTicTacToe.Infrastructure\Pixelbadger.EnterpriseTicTacToe.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="7.2.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="7.2.0" />
    <PackageReference Include="Mediator.Abstractions" Version="3.0.1" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
